### ISSUE TITLE
some problem about the code of test 

### ISSUE THREAD

**Issue by DIGI1919** [ucb-bar/riscv-mini#65]
After cloning , I start with the code of "make compile " and then i run the test of "test". but some of the unit test failed with output:
`[info] - should be equivalent to AluSimple *** FAILED ***
[info]   java.io.IOException: Cannot run program "z3" (in directory "/home/digi/code/scala/test/riscv-mini2"): error=2, 没有那个文件或目录
[info]   at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[info]   at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[info]   at os.proc.proc$lzycompute$1(ProcessOps.scala:128)
[info]   at os.proc.proc$1(ProcessOps.scala:122)
[info]   at os.proc.spawn(ProcessOps.scala:135)
[info]   at chiseltest.formal.backends.smt.SMTLibSolverContext.<init>(SMTLibSolver.scala:212)
[info]   at chiseltest.formal.backends.smt.Z3SMTLib$.createContext(SMTLibSolver.scala:71)
[info]   at chiseltest.formal.backends.smt.SMTModelChecker.check(SMTModelChecker.scala:33)
[info]   at chiseltest.formal.backends.Maltese$.bmc(Maltese.scala:72)
[info]   at chiseltest.formal.Formal$.executeOp(Formal.scala:82)
[info]   ...
[info]   Cause: java.io.IOException: error=2, 没有那个文件或目录
[info]   at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[info]   at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
[info]   at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
[info]   at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[info]   at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[info]   at os.proc.proc$lzycompute$1(ProcessOps.scala:128)
[info]   at os.proc.proc$1(ProcessOps.scala:122)
[info]   at os.proc.spawn(ProcessOps.scala:135)
[info]   at chiseltest.formal.backends.smt.SMTLibSolverContext.<init>(SMTLibSolver.scala:212)
[info]   at chiseltest.formal.backends.smt.Z3SMTLib$.createContext(SMTLibSolver.scala:71)
[info]   ...`
So i run run the test of unit individually. and find that the error come from the code :
` verify(new AluEquivalenceCheck(new AluArea(32)), Seq(BoundedCheck(1)))`
is it because of the lack of some bulid-commend?  so how can i solve it and avoid the mistake next time ?

**Comment by DIGI1919** [comment]
> I have solved this problem,and explain in my blog. https://blog.csdn.net/qq_42622433/article/details/136556479

thanks a lot
